import { describe, expect, it } from 'vitest';
import { addBuffs, computeDamage } from './damage';
import { CHARACTERS } from '../data/characters';
import { getWeapon } from '../data/weapons';
import { DEFAULT_BUFFS, NO_ARTIFACTS, resolvePreset, resolveSetPicks } from '../data/presets';
import { resolveSetBuffs } from '../data/artifactSets';
import { ENEMIES } from '../data/enemies';
import { talentRowsFor } from '../data/generated/talents';
import { TALENTS, signatureTalent } from '../data/talents';
import { baseStatsAt } from '../data/levelStats';

/**
 * Data-accuracy audit for Baizhu, run against three independent sources.
 *
 * Every number asserted here was cross-checked on 2026-09-20 against:
 *   • genshin-db v5.2.13            (the dataset our generators read)
 *   • damage.paimon.app             (Nuxt bundle, `c052070.js`)
 *   • genshin.aspirine.su           (plain `js/db.js`)
 *
 * Where the three disagree with us, the test documents the disagreement rather
 * than asserting our value, so a fix has to consciously flip the expectation.
 */

const baizhu = CHARACTERS.find((c) => c.id === 'baizhu')!;
const enemy = ENEMIES[0];

describe('Baizhu — base stats agree with all three sources', () => {
  it('level 90 base HP / ATK / DEF match genshin-db', () => {
    // genshin-db stats(90): hp 13348.0427932 / attack 192.5385949 / defense 499.5603405
    // aspirine hp_base 1039.1188 + curve; paimon identical base + promotion table.
    const curve = baseStatsAt('baizhu', 90)!;
    expect(Math.round(curve.hp)).toBe(13348);
    expect(Math.round(curve.atk * 100) / 100).toBe(192.54);
    expect(Math.round(curve.def)).toBe(500);
  });

  it('ascension stat is HP% and the true value is 0.288', () => {
    expect(baizhu.ascension.type).toBe('hp%');
    expect(baizhu.ascension.value).toBeCloseTo(0.288, 3);
  });

  it('the level curve keeps the ascension stat at full precision', () => {
    const curve = baseStatsAt('baizhu', 90)!;
    // All three sources report 28.8%, not 29%. FIXED 2026-09-21: the curve is
    // now generated by scripts/generate-level-stats.mjs and no longer rounded
    // to 2 dp, so every step is exact: 0.072 / 0.144 / 0.216 / 0.288.
    expect(curve.spec).toBeCloseTo(0.288, 6);
    expect(curve.spec).not.toBeCloseTo(0.29, 4);
    const steps = [41, 51, 71, 81].map((lv) => baseStatsAt('baizhu', lv)!.spec);
    expect(steps).toEqual([0.072, 0.144, 0.216, 0.288]);
  });

  it('scaling is HP (skill + burst both scale off Max HP)', () => {
    expect(baizhu.scaling).toBe('hp');
  });
});

describe('Baizhu — talent multipliers', () => {
  const rows = talentRowsFor('baizhu')!;
  const row = (label: string) => rows.find((r) => r.label === label)!;

  it('level-10 values match genshin-db and aspirine', () => {
    // genshin-db combat1 param1..param5 at index 9.
    expect(row('1-Hit DMG').values[9]).toBeCloseTo(0.672667, 6);
    expect(row('2-Hit DMG').values[9]).toBeCloseTo(0.655646, 6);
    expect(row('4-Hit DMG').values[9]).toBeCloseTo(0.974477, 6);
    expect(row('Charged Attack DMG').values[9]).toBeCloseTo(2.17872, 5);
    expect(row('Skill DMG').values[9]).toBeCloseTo(1.4256, 4);
    expect(row('Spiritvein DMG').values[9]).toBeCloseTo(1.747152, 6);
  });

  it('every damage row is Dendro (catalyst — no physical normals)', () => {
    for (const r of rows.filter((r) => r.isDamage)) expect(r.element).toBe('dendro');
  });

  it('3-Hit DMG rolls twice, and the combo total says so', () => {
    // genshin-db label: "3-Hit DMG|{param3:F1P}×2"
    // aspirine:        normal_hit_3 -> items:[{hits:2, ...}]
    // paimon.app:      "3段ダメージ|{param3:F1P}×2"
    // FIXED 2026-09-21: generate-talents.mjs now reads the ×N back out of the
    // format string instead of dropping it, so 52 labels across 34 characters
    // stopped under-reporting.
    expect(row('3-Hit DMG').hits).toBe(2);
    const trueCombo =
      row('1-Hit DMG').values[9] + row('2-Hit DMG').values[9] + row('3-Hit DMG').values[9] * 2 + row('4-Hit DMG').values[9];
    expect(trueCombo).toBeCloseTo(3.114288, 6);
  });
});

describe('Baizhu — which talent the site treats as his signature', () => {
  it('the engine picks the Normal Attack combo, not his Burst', () => {
    const sig = signatureTalent('baizhu')!;
    expect(sig.key).toBe('normal');
    // 3.114, not the 2.709 the hand-committed table carried: the summary is now
    // generated from the per-hit rows, so the ×2 on his 3-Hit reaches it.
    expect(sig.multiplier).toBeCloseTo(3.114, 3);
  });

  it('the summary table agrees with the per-hit table', () => {
    // The invariant that makes both files safe to regenerate: TALENTS is
    // derive(generated/talents.ts). scripts/generate-talents-summary.mjs writes
    // it that way, and npm run check:data re-derives it independently.
    const rows = talentRowsFor('baizhu')!;
    const combo = rows
      .filter((r) => r.isDamage && r.group === 'normal')
      .reduce((s, r) => s + r.values[9] * r.hits, 0);
    expect(combo).toBeCloseTo(TALENTS['baizhu'].normal, 3);
    expect(TALENTS['baizhu'].normal).toBeCloseTo(3.114, 3);
  });

  it('characters.ts advertises a Burst that is never used', () => {
    // signatureTalent() always resolves for baizhu, so skillName/skillMultiplier
    // are dead fallbacks — and they contradict what the engine actually does.
    expect(baizhu.skillName).toBe('Holistic Revivification (Burst)');
    expect(baizhu.skillMultiplier).toBe(1.6);
    // Neither 1.6 nor the burst's 1.747 is what the engine multiplies by.
    expect(signatureTalent('baizhu')!.multiplier).not.toBeCloseTo(baizhu.skillMultiplier, 3);
  });
});

describe('Baizhu — engine output under the site preset panel', () => {
  const weapon = getWeapon(baizhu.bestWeapon)!;

  it('home-page preset row (full artifact preset + set buffs, no reaction)', () => {
    const attackType = signatureTalent('baizhu')!.key;
    const buffs = addBuffs(DEFAULT_BUFFS, resolveSetBuffs(resolveSetPicks(baizhu), baizhu.element, attackType));
    const r = computeDamage({
      character: baizhu,
      weapon,
      artifacts: resolvePreset(baizhu),
      buffs,
      enemy,
      characterLevel: 90,
      amplified: 'none',
      transformative: 'none',
    });
    // eslint-disable-next-line no-console
    console.log('[preset panel]', {
      attackType,
      totalHP: Math.round(r.totalHP),
      totalATK: Math.round(r.totalATK),
      critRate: r.critRate.toFixed(3),
      critDMG: r.critDMG.toFixed(3),
      dmgBonus: r.dmgBonus.toFixed(3),
      multiplier: r.skillMultiplier,
      label: r.skillLabel,
      nonCrit: Math.round(r.nonCrit),
      expected: Math.round(r.expected),
    });
    // The headline number on the home page is a Normal Attack combo multiplied
    // by ATK, because normals scale off ATK even for a Max-HP character (see
    // ALT_SCALING_ATTACKS in lib/damage.ts).
    //
    // It moved 5,626 -> 6,468 (+15.0%) once the ×N fix reached the summary
    // table: his 3-Hit lands twice, and 3.114 / 2.709 = 1.1495. The old 5,627
    // was also a knife-edge rounding artefact of a hand-rounded base ATK.
    expect(r.expected).toBeCloseTo(6467.67, 1);
    expect(Math.round(r.expected)).toBe(6468);
    expect(r.element).toBe('dendro');
    expect(attackType).toBe('normal');
    // CONTRADICTION — the preset card reads `scaling: 'hp'` from characters.ts
    // and names his Burst, but the number shown is neither.
    expect(r.scaling).toBe('atk');
    expect(baizhu.scaling).toBe('hp');
  });

  it('bare panel (character + weapon only) matches the Klee reference conditions', () => {
    const r = computeDamage({
      character: baizhu,
      weapon,
      artifacts: NO_ARTIFACTS,
      buffs: DEFAULT_BUFFS,
      enemy,
      characterLevel: 90,
      amplified: 'none',
      transformative: 'none',
    });
    // eslint-disable-next-line no-console
    console.log('[bare panel]', {
      totalHP: Math.round(r.totalHP),
      totalATK: Math.round(r.totalATK),
      critRate: r.critRate.toFixed(3),
      critDMG: r.critDMG.toFixed(3),
      multiplier: r.skillMultiplier,
      label: r.skillLabel,
      nonCrit: Math.round(r.nonCrit),
      expected: Math.round(r.expected),
      defMultiplier: r.defMultiplier.toFixed(4),
      resMultiplier: r.resMultiplier.toFixed(4),
    });
    expect(r.totalHP).toBeGreaterThan(13000);
    expect(r.expected).toBeGreaterThan(0);
  });

  it('Spiritvein DMG (burst) is computed off Max HP', () => {
    const r = computeDamage({
      character: baizhu,
      weapon,
      artifacts: NO_ARTIFACTS,
      buffs: DEFAULT_BUFFS,
      enemy,
      characterLevel: 90,
      attackType: 'burst',
      skillMultiplier: 1.747152,
      element: 'dendro',
      scaling: 'hp',
      amplified: 'none',
      transformative: 'none',
    });
    expect(r.scaling).toBe('hp');
    expect(r.baseStat).toBeCloseTo(r.totalHP, 6);
    // eslint-disable-next-line no-console
    console.log('[burst Spiritvein]', { baseStat: Math.round(r.baseStat), nonCrit: Math.round(r.nonCrit), expected: Math.round(r.expected) });
  });
});

describe('Baizhu — constellation modelling gap', () => {
  it('KNOWN BUG — C2 and C6 do not feed the engine', () => {
    // src/data/constellations.ts CONSTELLATION_EFFECTS covers only 5 characters.
    // Baizhu C2 adds an extra Spiritvein hit and C6 adds +8% Max HP worth of
    // Spiritvein damage; neither is represented, so picking them changes nothing.
    const rows = talentRowsFor('baizhu')!;
    expect(rows.filter((r) => /gossamer|spiritvein/i.test(r.label)).length).toBe(1);
  });
});

/**
 * Site-wide consequences of the baseline drift, exercised through the engine so
 * the damage impact is visible rather than just the raw field mismatch.
 */
describe('site-wide — ascension stat type', () => {
  const weaponFor = (id: string) => getWeapon(CHARACTERS.find((c) => c.id === id)!.bestWeapon)!;

  const bare = (id: string) => {
    const c = CHARACTERS.find((x) => x.id === id)!;
    return computeDamage({
      character: c,
      weapon: weaponFor(id),
      artifacts: NO_ARTIFACTS,
      buffs: DEFAULT_BUFFS,
      enemy,
      characterLevel: 90,
      amplified: 'none',
      transformative: 'none',
    });
  };

  it('Qiqi no longer gets +22% ATK from what is really Healing Bonus', () => {
    // genshin-db substatType = FIGHT_PROP_HEAL_ADD (Healing Bonus, 22.15% at A6),
    // which contributes nothing to damage. FIXED 2026-09-21: the type is now
    // 'heal%', which statBag() deliberately ignores, and the curve carries the
    // real 0.2215 instead of a 2-dp 0.22.
    const c = CHARACTERS.find((x) => x.id === 'qiqi')!;
    expect(c.ascension.type).toBe('heal%');
    expect(baseStatsAt('qiqi', 90)!.spec).toBeCloseTo(0.2215, 6);

    const r = bare('qiqi');
    const ratio = r.totalATK / r.baseATK;
    // eslint-disable-next-line no-console
    console.log('[qiqi]', { baseATK: Math.round(r.baseATK), totalATK: Math.round(r.totalATK), ratio: ratio.toFixed(4) });
    // Before the fix this was 1.2200; now her ATK is untouched by ascension.
    expect(ratio).toBeCloseTo(1.0, 6);
  });

  it('Jean and Jahoda carry the same real Healing Bonus and are also unaffected', () => {
    // Both were typed 'atk%' with a curve of 0, so they never showed a wrong
    // number — but the data claimed they had an ATK ascension they do not have.
    const jean = CHARACTERS.find((c) => c.id === 'jean')!;
    const jahoda = CHARACTERS.find((c) => c.id === 'jahoda')!;
    expect(jean.ascension.type).toBe('heal%');
    expect(jahoda.ascension.type).toBe('heal%');
    expect(baseStatsAt('jean', 90)!.spec).toBeCloseTo(0.2215, 6);
    expect(baseStatsAt('jahoda', 90)!.spec).toBeCloseTo(0.1846, 6);
    // No damage stat leaks out of a heal% ascension.
    expect(bare('jean').totalATK / bare('jean').baseATK).toBeCloseTo(1.0, 6);
    expect(bare('jahoda').totalATK / bare('jahoda').baseATK).toBeCloseTo(1.0, 6);
  });

  it('every character that really has Healing Bonus is typed heal%', () => {
    // genshin-db FIGHT_PROP_HEAL_ADD covers exactly these three.
    const healers = CHARACTERS.filter((c) => c.ascension.type === 'heal%').map((c) => c.id).sort();
    expect(healers).toEqual(['jahoda', 'jean', 'qiqi']);
  });
});

describe('site-wide — multi-instance talents', () => {
  it('the ×N in genshin-db labels is read back into hits', () => {
    // FIXED 2026-09-21: generate-talents.mjs used to keep only the label and
    // throw away the format string, losing the ×N. It now parses it, which
    // recovered 52 labels across 34 characters. Klee's three bombs stay in
    // HIT_COUNT_OVERRIDE because the dataset does not mark them at all.
    const known = [
      ['baizhu', '3-Hit DMG', 2],
      ['keqing', 'Consecutive Slash DMG', 8],
      ['zhongli', '5-Hit DMG', 4],
      ['ayaka', 'Charged Attack DMG', 3],
      ['alhaitham', '3-Mirror Projection Attack DMG', 3],
      ['xiangling', '4-Hit DMG', 4], // "*4", not "×4"
      ['kazuha', '5-Hit DMG', 3],
      ['skirk', 'Slash DMG', 5],
    ] as const;
    for (const [id, label, expectedHits] of known) {
      const row = talentRowsFor(id)!.find((r) => r.label === label)!;
      expect(row, `${id} · ${label}`).toBeDefined();
      expect(row.hits, `${id} · ${label}`).toBe(expectedHits);
    }
  });

  it('no multi-hit row has a count of 0 or 1 by accident', () => {
    // A row is multi-hit only when the label says so; every count must be >= 1.
    for (const id of ['baizhu', 'keqing', 'zhongli', 'ganyu', 'klee']) {
      for (const row of talentRowsFor(id)!) {
        expect(row.hits, `${id} · ${row.label}`).toBeGreaterThanOrEqual(1);
        expect(Number.isInteger(row.hits), `${id} · ${row.label}`).toBe(true);
      }
    }
  });
});

/**
 * The generators are the only writers of levelStats.ts and characters.ts, so
 * the two must agree. These assertions fail loudly if either drifts again.
 */
describe('site-wide — generated data agrees with itself', () => {
  it('characters.ts base stats equal the level-90 curve', () => {
    const drift = [];
    for (const c of CHARACTERS) {
      const curve = baseStatsAt(c.id, 90);
      if (!curve) { drift.push(`${c.id}: no curve`); continue; }
      if (Math.abs(curve.hp - c.baseHP) > 1e-4) drift.push(`${c.id}: hp ${c.baseHP} vs ${curve.hp}`);
      if (Math.abs(curve.atk - c.baseATK) > 1e-4) drift.push(`${c.id}: atk ${c.baseATK} vs ${curve.atk}`);
      if (Math.abs(curve.def - c.baseDEF) > 1e-4) drift.push(`${c.id}: def ${c.baseDEF} vs ${curve.def}`);
    }
    expect(drift).toEqual([]);
  });

  it('ascension.value is the raw level-90 curve value, not the bonus alone', () => {
    // lib/damage.ts subtracts the baked-in base (0.05 CR / 0.5 CD) from
    // curve.spec. `value` is only a fallback, but it must speak the same
    // language or a missing curve would double-count.
    const drift = [];
    for (const c of CHARACTERS) {
      const curve = baseStatsAt(c.id, 90)!;
      if (Math.abs(curve.spec - c.ascension.value) > 1e-4) {
        drift.push(`${c.id}: value ${c.ascension.value} vs curve ${curve.spec}`);
      }
    }
    expect(drift).toEqual([]);
  });

  it('Lauma really has 115.2 EM, not the 315 she used to carry', () => {
    const lauma = CHARACTERS.find((c) => c.id === 'lauma')!;
    expect(lauma.ascension.type).toBe('em');
    expect(lauma.ascension.value).toBeCloseTo(115.2, 6);
  });

  it('row.scaling honours an explicit stat in the format string', () => {
    // The dataset spells out the stat when it is not ATK, e.g.
    // "Breakthrough Barb DMG|{param7:F2P} Max HP". Those rows used to be
    // multiplied by ATK.
    const row = (id: string, label: string, group?: string) =>
      talentRowsFor(id)!.find((r) => r.label === label && (!group || r.group === group))!;
    expect(row('yelan', 'Breakthrough Barb DMG').scaling).toBe('hp');
    expect(row('columbina', 'Moondew Cleanse DMG').scaling).toBe('hp');
    expect(row('kuki-shinobu', 'Single Instance DMG').scaling).toBe('hp');
    expect(row('xilonen', 'Blade Roller 1-Hit DMG').scaling).toBe('def');
    // Gorou has a "Skill DMG" in both the skill and the burst talent; only the
    // burst one carries the DEF suffix.
    expect(row('gorou', 'Skill DMG', 'burst').scaling).toBe('def');
    expect(row('yun-jin', 'Charge Level 2 DMG').scaling).toBe('def');
    expect(row('zibai', "Spirit Steed's Stride 1-Hit DMG").scaling).toBe('def');
    expect(row('linnea', 'Lumi Million Ton Crush DMG').scaling).toBe('def');
    expect(row('nefer', 'Phantasm Performance 3-Hit DMG (Shades)').scaling).toBe('em');
    expect(row('lauma', '2-Hit Hold DMG').scaling).toBe('em');
  });

  it('dual-stat rows keep a single-stat fallback rather than dropping a term', () => {
    // "ATK+Elemental Mastery" needs both; one `scaling` field cannot express
    // it, so these deliberately stay on the group-derived value.
    const alhaitham = talentRowsFor('alhaitham')!.find((r) => r.label === 'Rush Attack DMG')!;
    expect(alhaitham.scaling).toBe('atk');
    const dehya = talentRowsFor('dehya')!.find((r) => r.label === 'Flame-Mane\'s Fist DMG')!;
    expect(dehya.scaling).toBe('atk');
  });
});

describe('site-wide — bow grouping (the shot family is the charged attack)', () => {
  const groupOf = (charId: string, label: string) =>
    talentRowsFor(charId)!.find((r) => r.label === label)?.group;

  it('puts the aimed-shot family of a bow normal attack under charged', () => {
    // A bow's combat1 is not a melee combo: it also carries the uncharged aimed
    // shot and the character's own arrows, which are the charged attack's real
    // shape. Leaving them in `normal` made that group a junk drawer — Ganyu's
    // normal summed to 14.5 instead of the 5.2 combo.
    expect(groupOf('ganyu', 'Aimed Shot')).toBe('charged');
    expect(groupOf('ganyu', 'Aimed Shot Charge Level 1')).toBe('charged');
    expect(groupOf('ganyu', 'Frostflake Arrow DMG')).toBe('charged');
    expect(groupOf('lyney', 'Aimed Shot Charge Level 1')).toBe('charged');
    // The melee-style hit sequence stays in normal.
    expect(groupOf('ganyu', '1-Hit DMG')).toBe('normal');
  });

  it('keeps a bow whose best hit is the combo on normal', () => {
    // Yoimiya's 7.62 combo outranks her 3.39 charged shot, so the engine should
    // still pick `normal` for her.
    expect(signatureTalent('yoimiya')!.key).toBe('normal');
    expect(signatureTalent('ganyu')!.key).toBe('charged');
  });

  it('does not drag non-bow talents into charged', () => {
    // The rule is bow-only on purpose: these are charged-attack hits whose
    // labels never say "Charged", and a site-wide version of the rule moved 19
    // non-bow rows. They must stay where the label put them.
    expect(groupOf('xilonen', 'Blade Roller 1-Hit DMG')).toBe('normal');
    expect(groupOf('ningguang', 'DMG per Star Jade')).toBe('normal');
    expect(groupOf('itto', 'Arataki Kesagiri Combo Slash DMG')).toBe('normal');
  });
});

describe('site-wide — invariants the Diff-mode baseline depends on', () => {
  // A baseline keys rows by id, so ids must be unique within a character —
  // otherwise two different hits would collapse onto one comparison.
  it('talent row ids are unique within every character', () => {
    const collisions: string[] = [];
    for (const c of CHARACTERS) {
      const rows = talentRowsFor(c.id);
      if (!rows) continue;
      const seen = new Set<string>();
      for (const r of rows) {
        if (seen.has(r.id)) collisions.push(`${c.id}:${r.id}`);
        seen.add(r.id);
      }
    }
    expect(collisions).toEqual([]);
  });

  // ...but they are NOT namespaced by character: generated ids look like
  // "combat1-0-1-hit-dmg" and repeat verbatim across characters. That is why a
  // baseline has to carry the character it was pinned on and be ignored
  // elsewhere — otherwise it would match row-for-row and report garbage rather
  // than failing loudly.
  it('row ids repeat across characters, so a baseline must be character-scoped', () => {
    const baizhuIds = new Set(talentRowsFor('baizhu')!.map((r) => r.id));
    const shared = talentRowsFor('ganyu')!.filter((r) => baizhuIds.has(r.id)).map((r) => r.id);
    expect(shared).toContain('combat1-0-1-hit-dmg');
  });
});
