import { describe, expect, it } from 'vitest';
import { addBuffs, computeDamage } from './damage';
import { CHARACTERS } from '../data/characters';
import { getWeapon, WEAPONS } from '../data/weapons';
import { DEFAULT_BUFFS, NO_ARTIFACTS, resolvePreset, resolveSetPicks } from '../data/presets';
import { ARTIFACT_SETS, resolveSetBuffs } from '../data/artifactSets';
import { ENEMIES } from '../data/enemies';
import { talentRowsFor } from '../data/generated/talents';
import { TALENTS, signatureTalent } from '../data/talents';
import { baseStatsAt } from '../data/levelStats';
import { CONSTELLATION_EFFECTS, PASSIVE_EFFECTS, constellationBuffs } from '../data/constellations';
import { WEAPON_PASSIVE_EFFECTS, weaponBuffAt } from '../data/weaponPassives';
import { weaponPassiveFor } from '../data/generated/weaponPassives';
import { effectiveTalentLevels, signatureMultiplierAt } from '../components/calculator/draft';

/**
 * Data-accuracy audit: Baizhu in depth (the original template) plus three
 * differently-shaped characters (Fischl / Neuvillette / Itto), the artifact-set
 * and enemy tables, and the modelling-gap disclosures the UI makes.
 *
 * Every number asserted here was cross-checked on 2026-09-20/21 against:
 *   • genshin-db v5.2.13            (the dataset our generators read)
 *   • damage.paimon.app             (Nuxt bundle, `c052070.js`)
 *   • genshin.aspirine.su           (plain `js/db.js`)
 *
 * Where the three disagree with us, the test documents the disagreement rather
 * than asserting our value, so a fix has to consciously flip the expectation.
 */

const baizhu = CHARACTERS.find((c) => c.id === 'baizhu')!;
const enemy = ENEMIES[0];

describe('Baizhu — base stats agree with all three sources', () => {
  it('level 90 base HP / ATK / DEF match genshin-db', () => {
    // genshin-db stats(90): hp 13348.0427932 / attack 192.5385949 / defense 499.5603405
    // aspirine hp_base 1039.1188 + curve; paimon identical base + promotion table.
    const curve = baseStatsAt('baizhu', 90)!;
    expect(Math.round(curve.hp)).toBe(13348);
    expect(Math.round(curve.atk * 100) / 100).toBe(192.54);
    expect(Math.round(curve.def)).toBe(500);
  });

  it('ascension stat is HP% and the true value is 0.288', () => {
    expect(baizhu.ascension.type).toBe('hp%');
    expect(baizhu.ascension.value).toBeCloseTo(0.288, 3);
  });

  it('the level curve keeps the ascension stat at full precision', () => {
    const curve = baseStatsAt('baizhu', 90)!;
    // All three sources report 28.8%, not 29%. FIXED 2026-09-21: the curve is
    // now generated by scripts/generate-level-stats.mjs and no longer rounded
    // to 2 dp, so every step is exact: 0.072 / 0.144 / 0.216 / 0.288.
    expect(curve.spec).toBeCloseTo(0.288, 6);
    expect(curve.spec).not.toBeCloseTo(0.29, 4);
    const steps = [41, 51, 71, 81].map((lv) => baseStatsAt('baizhu', lv)!.spec);
    expect(steps).toEqual([0.072, 0.144, 0.216, 0.288]);
  });

  it('scaling is HP (skill + burst both scale off Max HP)', () => {
    expect(baizhu.scaling).toBe('hp');
  });
});

describe('Baizhu — talent multipliers', () => {
  const rows = talentRowsFor('baizhu')!;
  const row = (label: string) => rows.find((r) => r.label === label)!;

  it('level-10 values match genshin-db and aspirine', () => {
    // genshin-db combat1 param1..param5 at index 9.
    expect(row('1-Hit DMG').values[9]).toBeCloseTo(0.672667, 6);
    expect(row('2-Hit DMG').values[9]).toBeCloseTo(0.655646, 6);
    expect(row('4-Hit DMG').values[9]).toBeCloseTo(0.974477, 6);
    expect(row('Charged Attack DMG').values[9]).toBeCloseTo(2.17872, 5);
    expect(row('Skill DMG').values[9]).toBeCloseTo(1.4256, 4);
    expect(row('Spiritvein DMG').values[9]).toBeCloseTo(1.747152, 6);
  });

  it('every damage row is Dendro (catalyst — no physical normals)', () => {
    for (const r of rows.filter((r) => r.isDamage)) expect(r.element).toBe('dendro');
  });

  it('3-Hit DMG rolls twice, and the combo total says so', () => {
    // genshin-db label: "3-Hit DMG|{param3:F1P}×2"
    // aspirine:        normal_hit_3 -> items:[{hits:2, ...}]
    // paimon.app:      "3段ダメージ|{param3:F1P}×2"
    // FIXED 2026-09-21: generate-talents.mjs now reads the ×N back out of the
    // format string instead of dropping it, so 52 labels across 34 characters
    // stopped under-reporting.
    expect(row('3-Hit DMG').hits).toBe(2);
    const trueCombo =
      row('1-Hit DMG').values[9] + row('2-Hit DMG').values[9] + row('3-Hit DMG').values[9] * 2 + row('4-Hit DMG').values[9];
    expect(trueCombo).toBeCloseTo(3.114288, 6);
  });
});

describe('Baizhu — which talent the site treats as his signature', () => {
  it('the engine picks the Normal Attack combo, not his Burst', () => {
    const sig = signatureTalent('baizhu')!;
    expect(sig.key).toBe('normal');
    // 3.114, not the 2.709 the hand-committed table carried: the summary is now
    // generated from the per-hit rows, so the ×2 on his 3-Hit reaches it.
    expect(sig.multiplier).toBeCloseTo(3.114, 3);
  });

  it('the summary table agrees with the per-hit table', () => {
    // The invariant that makes both files safe to regenerate: TALENTS is
    // derive(generated/talents.ts). scripts/generate-talents-summary.mjs writes
    // it that way, and npm run check:data re-derives it independently.
    const rows = talentRowsFor('baizhu')!;
    const combo = rows
      .filter((r) => r.isDamage && r.group === 'normal')
      .reduce((s, r) => s + r.values[9] * r.hits, 0);
    expect(combo).toBeCloseTo(TALENTS['baizhu'].normal, 3);
    expect(TALENTS['baizhu'].normal).toBeCloseTo(3.114, 3);
  });

  it('characters.ts advertises a Burst that is never used', () => {
    // signatureTalent() always resolves for baizhu, so skillName/skillMultiplier
    // are dead fallbacks — and they contradict what the engine actually does.
    expect(baizhu.skillName).toBe('Holistic Revivification (Burst)');
    expect(baizhu.skillMultiplier).toBe(1.6);
    // Neither 1.6 nor the burst's 1.747 is what the engine multiplies by.
    expect(signatureTalent('baizhu')!.multiplier).not.toBeCloseTo(baizhu.skillMultiplier, 3);
  });
});

describe('Baizhu — engine output under the site preset panel', () => {
  const weapon = getWeapon(baizhu.bestWeapon)!;

  it('home-page preset row (full artifact preset + set buffs, no reaction)', () => {
    const attackType = signatureTalent('baizhu')!.key;
    const buffs = addBuffs(DEFAULT_BUFFS, resolveSetBuffs(resolveSetPicks(baizhu), baizhu.element, attackType));
    const r = computeDamage({
      character: baizhu,
      weapon,
      artifacts: resolvePreset(baizhu),
      buffs,
      enemy,
      characterLevel: 90,
      amplified: 'none',
      transformative: 'none',
    });
    // eslint-disable-next-line no-console
    console.log('[preset panel]', {
      attackType,
      totalHP: Math.round(r.totalHP),
      totalATK: Math.round(r.totalATK),
      critRate: r.critRate.toFixed(3),
      critDMG: r.critDMG.toFixed(3),
      dmgBonus: r.dmgBonus.toFixed(3),
      multiplier: r.skillMultiplier,
      label: r.skillLabel,
      nonCrit: Math.round(r.nonCrit),
      expected: Math.round(r.expected),
    });
    // The headline number on the home page is a Normal Attack combo multiplied
    // by ATK, because normals scale off ATK even for a Max-HP character (see
    // ALT_SCALING_ATTACKS in lib/damage.ts).
    //
    // It moved 5,626 -> 6,468 (+15.0%) once the ×N fix reached the summary
    // table: his 3-Hit lands twice, and 3.114 / 2.709 = 1.1495. The old 5,627
    // was also a knife-edge rounding artefact of a hand-rounded base ATK.
    expect(r.expected).toBeCloseTo(6467.67, 1);
    expect(Math.round(r.expected)).toBe(6468);
    expect(r.element).toBe('dendro');
    expect(attackType).toBe('normal');
    // CONTRADICTION — the preset card reads `scaling: 'hp'` from characters.ts
    // and names his Burst, but the number shown is neither.
    expect(r.scaling).toBe('atk');
    expect(baizhu.scaling).toBe('hp');
  });

  it('bare panel (character + weapon only) matches the Klee reference conditions', () => {
    const r = computeDamage({
      character: baizhu,
      weapon,
      artifacts: NO_ARTIFACTS,
      buffs: DEFAULT_BUFFS,
      enemy,
      characterLevel: 90,
      amplified: 'none',
      transformative: 'none',
    });
    // eslint-disable-next-line no-console
    console.log('[bare panel]', {
      totalHP: Math.round(r.totalHP),
      totalATK: Math.round(r.totalATK),
      critRate: r.critRate.toFixed(3),
      critDMG: r.critDMG.toFixed(3),
      multiplier: r.skillMultiplier,
      label: r.skillLabel,
      nonCrit: Math.round(r.nonCrit),
      expected: Math.round(r.expected),
      defMultiplier: r.defMultiplier.toFixed(4),
      resMultiplier: r.resMultiplier.toFixed(4),
    });
    expect(r.totalHP).toBeGreaterThan(13000);
    expect(r.expected).toBeGreaterThan(0);
  });

  it('Spiritvein DMG (burst) is computed off Max HP', () => {
    const r = computeDamage({
      character: baizhu,
      weapon,
      artifacts: NO_ARTIFACTS,
      buffs: DEFAULT_BUFFS,
      enemy,
      characterLevel: 90,
      attackType: 'burst',
      skillMultiplier: 1.747152,
      element: 'dendro',
      scaling: 'hp',
      amplified: 'none',
      transformative: 'none',
    });
    expect(r.scaling).toBe('hp');
    expect(r.baseStat).toBeCloseTo(r.totalHP, 6);
    // eslint-disable-next-line no-console
    console.log('[burst Spiritvein]', { baseStat: Math.round(r.baseStat), nonCrit: Math.round(r.nonCrit), expected: Math.round(r.expected) });
  });
});

describe('Baizhu — constellation modelling gap', () => {
  it('KNOWN BUG — C2 and C6 do not feed the engine', () => {
    // src/data/constellations.ts CONSTELLATION_EFFECTS covers only 5 characters.
    // Baizhu C2 adds an extra Spiritvein hit and C6 adds +8% Max HP worth of
    // Spiritvein damage; neither is represented, so picking them changes nothing.
    const rows = talentRowsFor('baizhu')!;
    expect(rows.filter((r) => /gossamer|spiritvein/i.test(r.label)).length).toBe(1);
  });
});

/**
 * The UI discloses which constellation / passive / weapon effects are shown as
 * text but feed nothing. These tests pin the disclosure to the data so a level
 * cannot be labelled "not modelled" while an entry exists, or vice versa.
 */
describe('modelling-gap disclosure — what the UI claims must match the tables', () => {
  const homa = getWeapon(baizhu.bestWeapon)!;
  const withMult = (mult: number) =>
    computeDamage({
      character: baizhu,
      weapon: homa,
      artifacts: NO_ARTIFACTS,
      buffs: DEFAULT_BUFFS,
      enemy,
      characterLevel: 90,
      skillMultiplier: mult,
      amplified: 'none',
      transformative: 'none',
    }).expected;

  it('an unmodelled character gets zero buff from any constellation level', () => {
    expect(CONSTELLATION_EFFECTS['baizhu']).toBeUndefined();
    for (const cn of [1, 2, 3, 4, 5, 6]) {
      expect(constellationBuffs('baizhu', cn)).toEqual(constellationBuffs('baizhu', 0));
    }
  });

  it('so C0 to C6 moves Baizhu only through the C3 / C5 talent bumps', () => {
    const levels = { normal: 10, skill: 10, burst: 10 };
    // His Burst — the talent C3 / C5 raise. Normal attacks are untouched by the
    // bumps, so for those C0 and C6 damage are literally identical.
    const atC0 = signatureMultiplierAt('baizhu', 'burst', levels);
    const atC6 = signatureMultiplierAt('baizhu', 'burst', effectiveTalentLevels('baizhu', levels, 6));
    expect(atC6).not.toBe(atC0);
    expect(withMult(atC6)).toBeGreaterThan(withMult(atC0));
  });

  it('Hu Tao C6 is modelled, so the note must not fire for it', () => {
    expect(CONSTELLATION_EFFECTS['hu-tao']?.[6]).toBeTruthy();
    expect(constellationBuffs('hu-tao', 6)).not.toEqual(constellationBuffs('hu-tao', 0));
  });

  it('Baizhu has no modelled ascension passives either', () => {
    expect(PASSIVE_EFFECTS['baizhu']).toBeUndefined();
  });
});

/**
 * The weapon table now comes from scripts/generate-weapons.mjs — 213 entries
 * straight from genshin-db instead of 63 hand-checked ones. These invariants
 * are what let a generated file be trusted like a curated one.
 */
describe('site-wide — generated weapon table', () => {
  const TYPES = ['polearm', 'bow', 'sword', 'catalyst', 'claymore'];
  const SECONDARY: string[] = [
    'atk%', 'hp%', 'def%', 'flatATK', 'flatHP', 'flatDEF',
    'critRate', 'critDMG', 'em', 'er', 'physical', 'dmg%', 'heal%',
  ];

  it('every entry is a well-formed, in-union row', () => {
    expect(WEAPONS.length).toBeGreaterThanOrEqual(213);
    const ids = new Set<string>();
    for (const w of WEAPONS) {
      expect(w.id).toMatch(/^[a-z0-9-]+$/);
      expect(w.name.length).toBeGreaterThan(0);
      expect(ids.has(w.id)).toBe(false);
      ids.add(w.id);
      expect(TYPES).toContain(w.weaponType);
      expect([4, 5]).toContain(w.rarity);
      expect(SECONDARY).toContain(w.secondary.type);
      expect(w.baseATK).toBeGreaterThan(0);
    }
  });

  it('no character points bestWeapon at a missing entry', () => {
    for (const c of CHARACTERS) {
      expect(getWeapon(c.bestWeapon), c.id).toBeTruthy();
    }
  });

  it('pins four known level-90 stat lines', () => {
    expect(getWeapon('staff-of-homa')).toMatchObject({ baseATK: 608, secondary: { type: 'critDMG', value: 0.662 } });
    expect(getWeapon('amos-bow')).toMatchObject({ baseATK: 608, secondary: { type: 'atk%', value: 0.496 } });
    expect(getWeapon('lost-prayer')).toMatchObject({ baseATK: 608, secondary: { type: 'critRate', value: 0.331 } });
    expect(getWeapon('sacrificial-fragments')).toMatchObject({ baseATK: 454, secondary: { type: 'em', value: 221 } });
  });
});

/**
 * Site-wide consequences of the baseline drift, exercised through the engine so
 * the damage impact is visible rather than just the raw field mismatch.
 */
describe('site-wide — ascension stat type', () => {
  const weaponFor = (id: string) => getWeapon(CHARACTERS.find((c) => c.id === id)!.bestWeapon)!;

  const bare = (id: string) => {
    const c = CHARACTERS.find((x) => x.id === id)!;
    return computeDamage({
      character: c,
      weapon: weaponFor(id),
      artifacts: NO_ARTIFACTS,
      buffs: DEFAULT_BUFFS,
      enemy,
      characterLevel: 90,
      amplified: 'none',
      transformative: 'none',
    });
  };

  it('Qiqi no longer gets +22% ATK from what is really Healing Bonus', () => {
    // genshin-db substatType = FIGHT_PROP_HEAL_ADD (Healing Bonus, 22.15% at A6),
    // which contributes nothing to damage. FIXED 2026-09-21: the type is now
    // 'heal%', which statBag() deliberately ignores, and the curve carries the
    // real 0.2215 instead of a 2-dp 0.22.
    const c = CHARACTERS.find((x) => x.id === 'qiqi')!;
    expect(c.ascension.type).toBe('heal%');
    expect(baseStatsAt('qiqi', 90)!.spec).toBeCloseTo(0.2215, 6);

    const r = bare('qiqi');
    const ratio = r.totalATK / r.baseATK;
    // eslint-disable-next-line no-console
    console.log('[qiqi]', { baseATK: Math.round(r.baseATK), totalATK: Math.round(r.totalATK), ratio: ratio.toFixed(4) });
    // Before the fix this was 1.2200; now her ATK is untouched by ascension.
    expect(ratio).toBeCloseTo(1.0, 6);
  });

  it('Jean and Jahoda carry the same real Healing Bonus and are also unaffected', () => {
    // Both were typed 'atk%' with a curve of 0, so they never showed a wrong
    // number — but the data claimed they had an ATK ascension they do not have.
    const jean = CHARACTERS.find((c) => c.id === 'jean')!;
    const jahoda = CHARACTERS.find((c) => c.id === 'jahoda')!;
    expect(jean.ascension.type).toBe('heal%');
    expect(jahoda.ascension.type).toBe('heal%');
    expect(baseStatsAt('jean', 90)!.spec).toBeCloseTo(0.2215, 6);
    expect(baseStatsAt('jahoda', 90)!.spec).toBeCloseTo(0.1846, 6);
    // No damage stat leaks out of a heal% ascension.
    expect(bare('jean').totalATK / bare('jean').baseATK).toBeCloseTo(1.0, 6);
    expect(bare('jahoda').totalATK / bare('jahoda').baseATK).toBeCloseTo(1.0, 6);
  });

  it('every character that really has Healing Bonus is typed heal%', () => {
    // genshin-db FIGHT_PROP_HEAL_ADD covers exactly these three.
    const healers = CHARACTERS.filter((c) => c.ascension.type === 'heal%').map((c) => c.id).sort();
    expect(healers).toEqual(['jahoda', 'jean', 'qiqi']);
  });
});

describe('site-wide — multi-instance talents', () => {
  it('the ×N in genshin-db labels is read back into hits', () => {
    // FIXED 2026-09-21: generate-talents.mjs used to keep only the label and
    // throw away the format string, losing the ×N. It now parses it, which
    // recovered 52 labels across 34 characters. Klee's three bombs stay in
    // HIT_COUNT_OVERRIDE because the dataset does not mark them at all.
    const known = [
      ['baizhu', '3-Hit DMG', 2],
      ['keqing', 'Consecutive Slash DMG', 8],
      ['zhongli', '5-Hit DMG', 4],
      ['ayaka', 'Charged Attack DMG', 3],
      ['alhaitham', '3-Mirror Projection Attack DMG', 3],
      ['xiangling', '4-Hit DMG', 4], // "*4", not "×4"
      ['kazuha', '5-Hit DMG', 3],
      ['skirk', 'Slash DMG', 5],
    ] as const;
    for (const [id, label, expectedHits] of known) {
      const row = talentRowsFor(id)!.find((r) => r.label === label)!;
      expect(row, `${id} · ${label}`).toBeDefined();
      expect(row.hits, `${id} · ${label}`).toBe(expectedHits);
    }
  });

  it('no multi-hit row has a count of 0 or 1 by accident', () => {
    // A row is multi-hit only when the label says so; every count must be >= 1.
    for (const id of ['baizhu', 'keqing', 'zhongli', 'ganyu', 'klee']) {
      for (const row of talentRowsFor(id)!) {
        expect(row.hits, `${id} · ${row.label}`).toBeGreaterThanOrEqual(1);
        expect(Number.isInteger(row.hits), `${id} · ${row.label}`).toBe(true);
      }
    }
  });
});

/**
 * The generators are the only writers of levelStats.ts and characters.ts, so
 * the two must agree. These assertions fail loudly if either drifts again.
 */
describe('site-wide — generated data agrees with itself', () => {
  it('characters.ts base stats equal the level-90 curve', () => {
    const drift = [];
    for (const c of CHARACTERS) {
      const curve = baseStatsAt(c.id, 90);
      if (!curve) { drift.push(`${c.id}: no curve`); continue; }
      if (Math.abs(curve.hp - c.baseHP) > 1e-4) drift.push(`${c.id}: hp ${c.baseHP} vs ${curve.hp}`);
      if (Math.abs(curve.atk - c.baseATK) > 1e-4) drift.push(`${c.id}: atk ${c.baseATK} vs ${curve.atk}`);
      if (Math.abs(curve.def - c.baseDEF) > 1e-4) drift.push(`${c.id}: def ${c.baseDEF} vs ${curve.def}`);
    }
    expect(drift).toEqual([]);
  });

  it('ascension.value is the raw level-90 curve value, not the bonus alone', () => {
    // lib/damage.ts subtracts the baked-in base (0.05 CR / 0.5 CD) from
    // curve.spec. `value` is only a fallback, but it must speak the same
    // language or a missing curve would double-count.
    const drift = [];
    for (const c of CHARACTERS) {
      const curve = baseStatsAt(c.id, 90)!;
      if (Math.abs(curve.spec - c.ascension.value) > 1e-4) {
        drift.push(`${c.id}: value ${c.ascension.value} vs curve ${curve.spec}`);
      }
    }
    expect(drift).toEqual([]);
  });

  it('Lauma really has 115.2 EM, not the 315 she used to carry', () => {
    const lauma = CHARACTERS.find((c) => c.id === 'lauma')!;
    expect(lauma.ascension.type).toBe('em');
    expect(lauma.ascension.value).toBeCloseTo(115.2, 6);
  });

  it('row.scaling honours an explicit stat in the format string', () => {
    // The dataset spells out the stat when it is not ATK, e.g.
    // "Breakthrough Barb DMG|{param7:F2P} Max HP". Those rows used to be
    // multiplied by ATK.
    const row = (id: string, label: string, group?: string) =>
      talentRowsFor(id)!.find((r) => r.label === label && (!group || r.group === group))!;
    expect(row('yelan', 'Breakthrough Barb DMG').scaling).toBe('hp');
    expect(row('columbina', 'Moondew Cleanse DMG').scaling).toBe('hp');
    expect(row('kuki-shinobu', 'Single Instance DMG').scaling).toBe('hp');
    expect(row('xilonen', 'Blade Roller 1-Hit DMG').scaling).toBe('def');
    // Gorou has a "Skill DMG" in both the skill and the burst talent; only the
    // burst one carries the DEF suffix.
    expect(row('gorou', 'Skill DMG', 'burst').scaling).toBe('def');
    expect(row('yun-jin', 'Charge Level 2 DMG').scaling).toBe('def');
    expect(row('zibai', "Spirit Steed's Stride 1-Hit DMG").scaling).toBe('def');
    expect(row('linnea', 'Lumi Million Ton Crush DMG').scaling).toBe('def');
    expect(row('nefer', 'Phantasm Performance 3-Hit DMG (Shades)').scaling).toBe('em');
    expect(row('lauma', '2-Hit Hold DMG').scaling).toBe('em');
  });

  it('dual-stat rows keep a single-stat fallback rather than dropping a term', () => {
    // "ATK+Elemental Mastery" needs both; one `scaling` field cannot express
    // it, so these deliberately stay on the group-derived value.
    const alhaitham = talentRowsFor('alhaitham')!.find((r) => r.label === 'Rush Attack DMG')!;
    expect(alhaitham.scaling).toBe('atk');
    const dehya = talentRowsFor('dehya')!.find((r) => r.label === 'Flame-Mane\'s Fist DMG')!;
    expect(dehya.scaling).toBe('atk');
  });
});

describe('site-wide — bow grouping (the shot family is the charged attack)', () => {
  const groupOf = (charId: string, label: string) =>
    talentRowsFor(charId)!.find((r) => r.label === label)?.group;

  it('puts the aimed-shot family of a bow normal attack under charged', () => {
    // A bow's combat1 is not a melee combo: it also carries the uncharged aimed
    // shot and the character's own arrows, which are the charged attack's real
    // shape. Leaving them in `normal` made that group a junk drawer — Ganyu's
    // normal summed to 14.5 instead of the 5.2 combo.
    expect(groupOf('ganyu', 'Aimed Shot')).toBe('charged');
    expect(groupOf('ganyu', 'Aimed Shot Charge Level 1')).toBe('charged');
    expect(groupOf('ganyu', 'Frostflake Arrow DMG')).toBe('charged');
    expect(groupOf('lyney', 'Aimed Shot Charge Level 1')).toBe('charged');
    // The melee-style hit sequence stays in normal.
    expect(groupOf('ganyu', '1-Hit DMG')).toBe('normal');
  });

  it('keeps a bow whose best hit is the combo on normal', () => {
    // Yoimiya's 7.62 combo outranks her 3.39 charged shot, so the engine should
    // still pick `normal` for her.
    expect(signatureTalent('yoimiya')!.key).toBe('normal');
    expect(signatureTalent('ganyu')!.key).toBe('charged');
  });

  it('does not drag non-bow talents into charged', () => {
    // The rule is bow-only on purpose: these are charged-attack hits whose
    // labels never say "Charged", and a site-wide version of the rule moved 19
    // non-bow rows. They must stay where the label put them.
    expect(groupOf('xilonen', 'Blade Roller 1-Hit DMG')).toBe('normal');
    expect(groupOf('ningguang', 'DMG per Star Jade')).toBe('normal');
    expect(groupOf('itto', 'Arataki Kesagiri Combo Slash DMG')).toBe('normal');
  });
});

describe('site-wide — invariants the Diff-mode baseline depends on', () => {
  // A baseline keys rows by id, so ids must be unique within a character —
  // otherwise two different hits would collapse onto one comparison.
  it('talent row ids are unique within every character', () => {
    const collisions: string[] = [];
    for (const c of CHARACTERS) {
      const rows = talentRowsFor(c.id);
      if (!rows) continue;
      const seen = new Set<string>();
      for (const r of rows) {
        if (seen.has(r.id)) collisions.push(`${c.id}:${r.id}`);
        seen.add(r.id);
      }
    }
    expect(collisions).toEqual([]);
  });

  // ...but they are NOT namespaced by character: generated ids look like
  // "combat1-0-1-hit-dmg" and repeat verbatim across characters. That is why a
  // baseline has to carry the character it was pinned on and be ignored
  // elsewhere — otherwise it would match row-for-row and report garbage rather
  // than failing loudly.
  it('row ids repeat across characters, so a baseline must be character-scoped', () => {
    const baizhuIds = new Set(talentRowsFor('baizhu')!.map((r) => r.id));
    const shared = talentRowsFor('ganyu')!.filter((r) => baizhuIds.has(r.id)).map((r) => r.id);
    expect(shared).toContain('combat1-0-1-hit-dmg');
  });
});

describe('site-wide — artifact set table', () => {
  const ELEMENTS: string[] = ['pyro', 'hydro', 'electro', 'cryo', 'anemo', 'geo', 'dendro', 'physical'];

  it('every set defines both a 2pc and a 4pc and ids are well-formed and unique', () => {
    const ids = new Set<string>();
    for (const s of ARTIFACT_SETS) {
      expect(s.id).toMatch(/^[a-z0-9]+(-[a-z0-9]+)*$/);
      expect(ids.has(s.id), `duplicate set id ${s.id}`).toBe(false);
      ids.add(s.id);
      expect(s.two, `${s.id} missing 2pc`).toBeTruthy();
      expect(s.four, `${s.id} missing 4pc`).toBeTruthy();
    }
  });

  it('no element bonus points outside ElementType', () => {
    for (const s of ARTIFACT_SETS) {
      for (const eff of [s.two, s.four]) {
        if (eff.elemDmg) expect(ELEMENTS, `${s.id} bad elemDmg element`).toContain(eff.elemDmg.element);
      }
    }
  });

  it('every set carries a note — conditional effects state their assumption', () => {
    for (const s of ARTIFACT_SETS) {
      expect(s.note, `${s.id} has no note`).toBeTruthy();
      expect(s.note!.length, `${s.id} note is a stub`).toBeGreaterThan(10);
    }
  });

  it('covers every rarity-4+ set: 45 modelled, 15 documented omissions', () => {
    expect(ARTIFACT_SETS.length).toBe(45);
    // The 15 omissions are justified in the artifactSets.ts header — the ones
    // listed here are the sets a visitor might otherwise think are missing.
    for (const skipped of ['Maiden Beloved', 'Lavawalker', "Long Night's Oath"]) {
      expect(ARTIFACT_SETS.some((s) => s.name === skipped), `${skipped} must stay omitted`).toBe(false);
    }
  });

  it('new sets feed the engine the way their notes claim', () => {
    // Instructor: 2pc EM + 4pc EM stack additively.
    const inst = resolveSetBuffs([{ id: 'instructor', pieces: 4 }], 'pyro', 'skill');
    expect(inst.em).toBe(200);
    // Berserker 4pc is deliberately unmodelled — only the 2pc CRIT applies.
    const bers = resolveSetBuffs([{ id: 'berserker', pieces: 4 }], 'physical', 'normal');
    expect(bers.critRate).toBe(0.12);
    // Flower of Paradise Lost feeds only the bloom-family reactions.
    const fpl = resolveSetBuffs([{ id: 'flower-of-paradise-lost', pieces: 4 }], 'dendro', 'burst');
    expect(fpl.reactionDmg).toEqual({ bloom: 0.4, hyperbloom: 0.4, burgeon: 0.4 });
  });
});

/**
 * Task 6 breadth — the Baizhu template applied to three different shapes:
 * a bow user (aimed-shot grouping), an HP-scaling charged-attack carry, and a
 * DEF-scaling claymore user. Every pinned number was cross-checked on
 * 2026-09-21 against genshin-db v5.2.13 (stats(90) and combatN param tables).
 */

describe('Fischl — bow user: aimed-shot grouping and the combat1 element caveat', () => {
  const fischl = CHARACTERS.find((c) => c.id === 'fischl')!;
  const rows = talentRowsFor('fischl')!;
  const row = (label: string) => rows.find((r) => r.label === label)!;

  it('level-90 base stats and ascension match genshin-db', () => {
    // gdb stats(90): hp 9189.3029266 / attack 244.2567708 / defense 593.79372675 / specialized 0.24
    const curve = baseStatsAt('fischl', 90)!;
    expect(Math.round(curve.hp)).toBe(9189);
    expect(Math.round(curve.atk * 100) / 100).toBe(244.26);
    expect(Math.round(curve.def)).toBe(594);
    expect(fischl.ascension).toEqual({ type: 'atk%', value: 0.24 });
  });

  it('the five normal hits sum to the advertised combo total', () => {
    // gdb combat1 param1..param5 at index 9: 0.8721 / 0.9248 / 1.1492 / 1.1407 / 1.4246
    const combo = ['1-Hit DMG', '2-Hit DMG', '3-Hit DMG', '4-Hit DMG', '5-Hit DMG'].reduce((s, l) => s + row(l).values[9], 0);
    expect(combo).toBeCloseTo(5.5114, 6);
    expect(signatureTalent('fischl')!.multiplier).toBeCloseTo(5.511, 3);
    expect(TALENTS['fischl'].normal).toBeCloseTo(5.511, 3);
  });

  it('Aimed Shot and Fully-Charged Aimed Shot live in the charged group', () => {
    // In-game the shot family IS the charged attack; the generator groups it
    // accordingly (gdb combat1 fully-charged param = 2.232, aimed = 0.867).
    expect(row('Aimed Shot').group).toBe('charged');
    expect(row('Aimed Shot').values[9]).toBeCloseTo(0.867, 6);
    expect(row('Fully-Charged Aimed Shot').values[9]).toBeCloseTo(2.232, 6);
  });

  it('KNOWN GAP — her physical normal combo is tagged Electro', () => {
    // genshin-db carries ONE element per talent; Fischl's combat1 text only
    // mentions Electro (the fully-charged shot), so generate-talents.mjs tags
    // every combat1 row Electro. In game the five normal shots are Physical.
    // Harmless against the default 10%-everything enemy, wrong against
    // Physical-RES exceptions (mechanicals). If combat1 elements are ever split
    // per row, this is the canary that must flip.
    for (const r of rows.filter((r) => r.isDamage && r.group === 'normal')) expect(r.element).toBe('electro');
  });

  it('engine output is stable under both panels', () => {
    const weapon = getWeapon(fischl.bestWeapon)!;
    const bare = computeDamage({
      character: fischl, weapon, artifacts: NO_ARTIFACTS, buffs: DEFAULT_BUFFS,
      enemy, characterLevel: 90, amplified: 'none', transformative: 'none',
    });
    expect(bare.expected).toBeCloseTo(2377.43, 1);
    const buffs = addBuffs(DEFAULT_BUFFS, resolveSetBuffs(resolveSetPicks(fischl), fischl.element, 'normal'));
    const preset = computeDamage({
      character: fischl, weapon, artifacts: resolvePreset(fischl), buffs,
      enemy, characterLevel: 90, amplified: 'none', transformative: 'none',
    });
    expect(preset.expected).toBeCloseTo(11464.52, 1);
  });
});

describe('Neuvillette — HP-scaling charged carry', () => {
  const neu = CHARACTERS.find((c) => c.id === 'neuvillette')!;
  const rows = talentRowsFor('neuvillette')!;
  const row = (label: string) => rows.find((r) => r.label === label)!;

  it('level-90 base stats and Crit DMG ascension match genshin-db', () => {
    // gdb stats(90): hp 14695.093176 / atk 208.32436678 / def 576.4157775 / specialized 0.884
    const curve = baseStatsAt('neuvillette', 90)!;
    expect(Math.round(curve.hp)).toBe(14695);
    expect(Math.round(curve.atk * 100) / 100).toBe(208.32);
    expect(neu.ascension).toEqual({ type: 'critDMG', value: 0.884 });
    expect(neu.scaling).toBe('hp');
  });

  it('the signature is the charged attack, and its two rows sum to the combo', () => {
    const charged = rows.filter((r) => r.isDamage && r.group === 'charged');
    expect(charged.map((r) => r.label).sort()).toEqual(['Charged Attack DMG', 'Charged Attack: Equitable Judgment']);
    expect(row('Charged Attack DMG').values[9]).toBeCloseTo(2.4624, 6);
    expect(row('Charged Attack: Equitable Judgment').values[9]).toBeCloseTo(0.14467, 6);
    const sig = signatureTalent('neuvillette')!;
    expect(sig.key).toBe('charged');
    expect(sig.multiplier).toBeCloseTo(2.607, 3);
  });

  it('bare-panel damage scales off Max HP, not ATK', () => {
    const r = computeDamage({
      character: neu, weapon: getWeapon(neu.bestWeapon)!, artifacts: NO_ARTIFACTS, buffs: DEFAULT_BUFFS,
      enemy, characterLevel: 90, amplified: 'none', transformative: 'none',
    });
    expect(r.scaling).toBe('hp');
    expect(r.baseStat).toBeCloseTo(r.totalHP, 6);
    expect(r.expected).toBeCloseTo(18761.8, 1);
  });
});

describe('Arataki Itto — DEF-scaling claymore', () => {
  const itto = CHARACTERS.find((c) => c.id === 'itto')!;
  const rows = talentRowsFor('itto')!;

  it('level-90 base stats and CRIT Rate ascension match genshin-db', () => {
    // gdb stats(90): def 959.15585376 / specialized 0.242 (CRIT Rate)
    const curve = baseStatsAt('itto', 90)!;
    expect(Math.round(curve.def)).toBe(959);
    expect(itto.ascension).toEqual({ type: 'critRate', value: 0.242 });
    expect(itto.scaling).toBe('def');
  });

  it('every combat1 row is Physical and sums to the 14.569 combo', () => {
    const normal = rows.filter((r) => r.isDamage && r.group === 'normal');
    for (const r of normal) expect(r.element).toBe('physical');
    const combo = normal.reduce((s, r) => s + r.values[9] * r.hits, 0);
    expect(combo).toBeCloseTo(14.569, 3);
    expect(TALENTS['itto'].normal).toBeCloseTo(14.569, 3);
  });

  it('the Burst carries no direct multiplier — damage comes from the empowered Normal combo', () => {
    // His combat3 grants the Oni King's Mudra state; the dataset's burst table
    // has no damage %, so TALENTS pins it at 0 and the Kesagiri rows live in
    // combat1. The preset card must not claim a burst multiplier.
    expect(TALENTS['itto'].burst).toBe(0);
    expect(rows.filter((r) => r.isDamage && r.group === 'burst')).toHaveLength(0);
  });

  it('bare-panel damage scales off DEF', () => {
    const r = computeDamage({
      character: itto, weapon: getWeapon(itto.bestWeapon)!, artifacts: NO_ARTIFACTS, buffs: DEFAULT_BUFFS,
      enemy, characterLevel: 90, amplified: 'none', transformative: 'none',
    });
    expect(r.scaling).toBe('def');
    expect(r.baseStat).toBeCloseTo(r.totalDEF, 6);
    expect(r.expected).toBeCloseTo(8391.35, 1);
  });
});

describe('site-wide — enemy table', () => {
  it('ENEMIES[0] stays the default target and every entry is well-formed', () => {
    expect(ENEMIES[0].id).toBe('hilichurl');
    const ids = new Set(ENEMIES.map((e) => e.id));
    expect(ids.size).toBe(ENEMIES.length);
    expect(ENEMIES.length).toBeGreaterThan(30);
    for (const e of ENEMIES) {
      expect(e.level).toBe(90);
      expect(e.resistances.default).toBeCloseTo(0.1, 6);
    }
  });

  it('the +70% Physical exception is limited to the documented mechanical family', () => {
    const mech = ENEMIES.filter((e) => (e.resistances.physical ?? 0) > 0.1).map((e) => e.id);
    expect(mech.sort()).toEqual(['perpetual-mechanical-array', 'ruin-guard', 'ruin-sentinel']);
    for (const e of ENEMIES) {
      for (const el of ['pyro', 'hydro', 'electro', 'cryo', 'anemo', 'geo', 'dendro'] as const) {
        expect(e.resistances[el]).toBeUndefined();
      }
    }
  });

  it('weekly bosses are all-10% — the standing trivia, now pinned', () => {
    for (const id of ['stormterror', 'azhdaha', 'la-signora', 'all-devouring-narwhal', 'shouki-no-kami']) {
      const e = ENEMIES.find((x) => x.id === id)!;
      expect(e, `${id} must be selectable`).toBeTruthy();
      expect(e.resistances).toEqual({ default: 0.1 });
    }
  });
});

/**
 * Brief #2 Task 1. Aether and Lumine used to print a confident headline above
 * an empty table: genshin-db stores the Traveler's kits under element-split
 * names ("Traveler (Anemo)"), so `talents('Aether')` found nothing and every
 * figure fell back to the placeholder in characters.ts. The generators now
 * resolve through the shared TALENT_NAME_OVERRIDE. The Miliastra pair
 * (Manekin / Manekina, v6.1 test characters) has no talent table anywhere —
 * for those the UI shows a "no talent data" notice instead of a number.
 */
describe('Traveler roster entries — real data at last', () => {
  it('aether and lumine resolve through the shared Traveler (Anemo) override', () => {
    const rows = talentRowsFor('aether');
    expect(rows?.length).toBeGreaterThan(0);
    // In game the siblings share every talent number; the site models both on
    // the Anemo kit (characters.ts note), so both map to the same table.
    expect(talentRowsFor('lumine')).toEqual(rows);
    const tornado = rows!.find((r) => r.label === 'Tornado DMG')!;
    expect(tornado.element).toBe('anemo');
    expect(tornado.values[9]).toBeCloseTo(1.4544, 6);
  });

  it('the physical melee combo is tagged physical, the Anemo kit Anemo', () => {
    const rows = talentRowsFor('aether')!;
    for (const r of rows.filter((r) => r.group === 'normal')) expect(r.element).toBe('physical');
    for (const r of rows.filter((r) => r.group === 'skill' || r.group === 'burst')) expect(r.element).toBe('anemo');
  });

  it('the summary table is derived from the rows, not the placeholder', () => {
    const rows = talentRowsFor('aether')!;
    const combo = rows
      .filter((r) => r.isDamage && r.group === 'normal')
      .reduce((s, r) => s + r.values[9] * r.hits, 0);
    expect(combo).toBeCloseTo(TALENTS['aether'].normal, 3);
    expect(TALENTS['aether'].normal).toBeCloseTo(5.336, 3);
  });
});

describe('the no-talent guard — exactly the Miliastra pair stays empty', () => {
  it('talentRowsFor is empty for precisely these ids, so the UI list cannot drift', () => {
    const missing = CHARACTERS.filter((c) => !c.unreleased && !(talentRowsFor(c.id)?.length ?? false)).map(
      (c) => c.id,
    );
    expect(missing).toEqual(['manekin', 'manekina']);
  });
});

// A passive description is "conditional" when it gates the buff behind an event
// (hits, skills, stacks, shields...). The house rule says such an entry must
// either model only the unconditional core or say in `note` what it assumes —
// so "conditional description && no note" is always a modelling bug.
const CONDITIONAL_RE = /\b(when|after|once|until|while|if|upon|hit(s|ting)?\b|defeats?|trigger\w*|stacks?\b|chance|shield)\b/i;

describe('weapon passive modelling — WEAPON_PASSIVE_EFFECTS integrity', () => {
  it('every modelled weapon id exists in WEAPONS and has generated passive data', () => {
    for (const id of Object.keys(WEAPON_PASSIVE_EFFECTS)) {
      expect(getWeapon(id), id).toBeTruthy();
      expect(weaponPassiveFor(id), id).toBeTruthy();
    }
  });

  it('every valueIndex is in range for every refinement of its weapon', () => {
    for (const [id, effect] of Object.entries(WEAPON_PASSIVE_EFFECTS)) {
      for (const [r, ref] of weaponPassiveFor(id)!.refinements.entries()) {
        for (const line of effect.lines) {
          expect(line.valueIndex, `${id} r${r + 1}`).toBeLessThan(ref.values.length);
        }
      }
    }
  });

  it('every conditional game effect discloses its assumption in note', () => {
    const silent: string[] = [];
    for (const [id, effect] of Object.entries(WEAPON_PASSIVE_EFFECTS)) {
      const desc = weaponPassiveFor(id)!.refinements[0].description;
      if (CONDITIONAL_RE.test(desc) && !effect.note) silent.push(id);
    }
    expect(silent).toEqual([]);
  });

  it('weaponBuffAt yields finite, non-negative contributions at max refine and stacks', () => {
    for (const [id, effect] of Object.entries(WEAPON_PASSIVE_EFFECTS)) {
      const buff = weaponBuffAt(id, 5, effect.maxStacks);
      for (const [stat, value] of Object.entries(buff)) {
        expect(Number.isFinite(value), `${id}.${stat}`).toBe(true);
        expect(value, `${id}.${stat}`).toBeGreaterThanOrEqual(0);
      }
    }
  });
});
